// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDccmywcZmJECsBIlJSB3pWQWziw6Tyvl0',
    appId: '1:895590588645:web:5f4118f682c9020855740c',
    messagingSenderId: '895590588645',
    projectId: 'fluttertp3appmobileav',
    authDomain: 'fluttertp3appmobileav.firebaseapp.com',
    storageBucket: 'fluttertp3appmobileav.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fWK62G4wlQPJ3maohmMxru2VaejdzRU',
    appId: '1:895590588645:android:f6915a61a7b50e2955740c',
    messagingSenderId: '895590588645',
    projectId: 'fluttertp3appmobileav',
    storageBucket: 'fluttertp3appmobileav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSR3TCpZbTsBXhQV81muFF2MwJ4Mg3tL8',
    appId: '1:895590588645:ios:44c97d5f48f5ab1f55740c',
    messagingSenderId: '895590588645',
    projectId: 'fluttertp3appmobileav',
    storageBucket: 'fluttertp3appmobileav.firebasestorage.app',
    iosBundleId: 'com.example.frontendtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSR3TCpZbTsBXhQV81muFF2MwJ4Mg3tL8',
    appId: '1:895590588645:ios:44c97d5f48f5ab1f55740c',
    messagingSenderId: '895590588645',
    projectId: 'fluttertp3appmobileav',
    storageBucket: 'fluttertp3appmobileav.firebasestorage.app',
    iosBundleId: 'com.example.frontendtp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDccmywcZmJECsBIlJSB3pWQWziw6Tyvl0',
    appId: '1:895590588645:web:6cca7cee6755da5f55740c',
    messagingSenderId: '895590588645',
    projectId: 'fluttertp3appmobileav',
    authDomain: 'fluttertp3appmobileav.firebaseapp.com',
    storageBucket: 'fluttertp3appmobileav.firebasestorage.app',
  );
}
